# Generated by Django 2.1.3 on 2018-12-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='testman', max_length=20),
            preserve_default=False,
        ),
    ]
